name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add current timestamp as env variable
      run: |
        echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Base Docker image
      run: docker build . --file Base.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:base-$TIMESTAMP && docker build . --file Base.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:latest
    - name: Build the Java 17 Docker image
      run: docker build . --file Java17.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:java17-$TIMESTAMP && docker build . --file Java17.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:java17-latest
    - name: Build the Python 3 Docker image
      run: docker build . --file Python3.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:python3-$TIMESTAMP && docker build . --file Python3.Dockerfile --tag ${{secrets.DOCKER_USER}}/runstart:python3-latest
    - name: Docker push images
      run: docker push --all-tags ${{secrets.DOCKER_USER}}/runstart
